#!/usr/bin/env python3

import sqlite

conn = sqlite3.connect('wizard_duels.db')
c = conn.cursor()

c.execute("""CREATE TABLE wizards (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL, 
  year INTEGER,
  house TEXT NOT NULL
  )
  """
)

c.execute("""CREATE TABLE houses (
  house TEXT PRIMARY KEY, 
  weakness TEXT NOT NULL,
  draw TEXT NOT NULL
  )
  """
)

c.execute("""CREATE TABLE spells (
  id INTEGER PRIMARY KEY,
  spell TEXT NOT NULL,
  description TEXT NOT NULL, 
  power INTEGER
  )
  """
)

c.execute("""CREATE TABLE results (
  name TEXT PRIMARY KEY, 
  wins INTEGER, 
  losses INTEGER
  )
  """
)

c.execute("""CREATE TABLE azkaban (
  name TEXT PRIMARY KEY, 
  victim1 TEXT NOT NULL, 
  victim2 TEXT NOT NULL,
  state TEXT NOT NULL
  )
  """
)
